spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: binarfud-challange6

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes

  # Define an empty placeholder for JWT secret
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION_MS}